"""create initial tables

Revision ID: e05cb91fbf80
Revises: 
Create Date: 2026-05-09 22:25:48.754946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e05cb91fbf80'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), nullable=False),
    sa.Column('rankings', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracked_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('github_username', sa.String(length=39), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracked_users_github_username'), 'tracked_users', ['github_username'], unique=True)
    op.create_table('user_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('commits_30d', sa.Integer(), nullable=False),
    sa.Column('prs_opened_30d', sa.Integer(), nullable=False),
    sa.Column('prs_merged_30d', sa.Integer(), nullable=False),
    sa.Column('issues_opened_30d', sa.Integer(), nullable=False),
    sa.Column('reviews_30d', sa.Integer(), nullable=False),
    sa.Column('stars_received', sa.Integer(), nullable=False),
    sa.Column('repos_count', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tracked_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_stats')
    op.drop_index(op.f('ix_tracked_users_github_username'), table_name='tracked_users')
    op.drop_table('tracked_users')
    op.drop_table('leaderboard_snapshots')
    # ### end Alembic commands ###
